### ISSUE TITLE
Question: Is this plugin still maintained?

### ISSUE THREAD

**Issue by R-Studio** [grafana/grafana-polystat-panel#169]
Hi all

First thanks for this really cool polystat plugin!
I will use this plugin for many further usecases, but it is a little bit buggy with Grafana 7.3.5 and the new "Plugin system".
So before I invest a lot of effort, is this plugin still maintained?

**Comment by matletix** [comment]
Hi,
This plugin is maintained by @grafana. It looks like @briangann is the main maintainer contributing and accepting PRs.
The repo didn't get any commit since last august, maintainers might have higher priority projects to work on :)
I also hope it's still maintained because it's a useful plugin to have in grafana !

**Comment by briangann** [comment]
It's currently being maintained, we just haven't had much time to dedicate to it. Please do file bugs, I expect to be able to spend more time on it in the near future.

**Comment by R-Studio** [comment]
Nice, then I use this plugin in my dashboards. Thanks for your feedback. 👍
