### ISSUE TITLE
Passing label values to clichthrough variable

### ISSUE THREAD

**Issue by heover1cks** [grafana/grafana-polystat-panel#192]
Hello, 

First of all, thank you for the great plugin. 
I am using it as system status dashboard, but I don't know how to pass label values to clichthrough. 

For example, 
`https://GRAFANA_URL/dashboard?var-project=${__cell_name}&var-owner=${__label_value.owner}&var-env=${__label_value.env}`
like this. 

Thanks a lot!

**Comment by a-mazed** [comment]
Try to use Templating - https://github.com/grafana/grafana-polystat-panel#templating

**Comment by jeremyschulman** [comment]
I am also looking for the same, and the existing templating of "__cell" I do not believe works for want I would like.  If I have a series of data that has fields "host" and "interface", then I would like to use ${__field.labels.host} and ${__field.labels.interface} in the clickThru so that I can pass each of these variables to another dashboard that accepts these values as separate variables.

For example "/d/dashboar-chlickthru?var-device=${__field.labels.host}&var-interface=${__field.lables.interface}"

Is this possible?

Thank you!
