### ISSUE TITLE
Bug: Tooltips don't disappear on mouse out

### ISSUE THREAD

**Issue by jackw** [grafana/grafana-polystat-panel#273]
Not sure if this has already been reported but when playing with Polystat plugin v2.0.8 in chrome on OSX when hovering over the panel tooltips are working great. However if I move the mouse outside of the polystat panel they remain until the Ploystat panel is unmounted.

![image](https://github.com/grafana/grafana-polystat-panel/assets/73201/ab47939a-f133-4ea3-a871-d8cdd614ce2d)

**Comment by briangann** [comment]
which version of grafana were you running?

I'm seeing this in G10, will try with older versions.  

The problem is worse than expected - you can end up with multiple tooltips following the mouse around other panels.

We do want to replace tippyjs, might be time to go ahead and do that.

thanks jack!

**Comment by jackw** [comment]
Yep, I was running it against `main` at the time. So `10.1.0-pre`.
