### ISSUE TITLE
Polystat 1.2.11 tooltip not showing in Grafana v9.5.19

### ISSUE THREAD

**Issue by dequeee** [grafana/grafana-polystat-panel#385]
Hi,

I am using Grafana and polystat to the following versions:
Grafana v9.5.19 and polystat plugin version: 1.2.11

After upgrading Grafana to version 9, I noticed that the tooltip generated by the polystat panel no longer works, in fact scrolling with the cursor on the cells, nothing appears. It would be useful to understand if it is a problem that has already occurred in the past, or if I need to update the version of the plugin, because the current version is not supported by version 9 of Grafana.

thanks,
Daniele

**Comment by briangann** [comment]
I did confirm that v1.2.11 with grafana 9.5.19 does not show tooltips, the underlying d3 package has changed since version Grafana 9.4+

The last working angular version appears to be 9.3.16.

It would be best to upgrade to the current react-based polystat plugin, which is currently 2.1.10.

The v1 (angular) releases are not supported going forward. Note that existing panels will auto-migrate their configurations when upgrading.

Thanks!
