### ISSUE TITLE
Does updating from Polystat 1.2.11 to last version keeps old panels usable?

### ISSUE THREAD

**Issue by dequeee** [grafana/grafana-polystat-panel#405]
By manually updating, so downloading the package and importing it by hand into the plugin directory, replacing the old one, can create problems with panels made in the previous version of polystat? Or does it automatically convert the old panels and they will be accessible immediately?

Are there other ways to import old panels into the new version? Maybe copy the JSON panel manually to a dashboard in the new version?

Or does it not work because of incompatibilities between versions?

Best regards!

**Comment by briangann** [comment]
the migration is automatic, i would backup your dashboard just in case you run into an issue

**Comment by birko999** [comment]
I've noticed one issue during upgrade from v1.2.11 to v2.1.8
I'm using "Default Clickthrough" with combination of "Global Aliasing - Regex Pattern". The issue is I need to filter out string prefix, which is inside polygon and at the same time I need to use this string without prefix in URL, which is used as click through to another dashboard. 

v1.2.11 - prefix "int_utilizationin" is successfully filtered out from URL
![image](https://github.com/user-attachments/assets/012e30b2-6231-47bd-bb91-ed38a4ad029a)

v2.1.8 - prefix "int_utilizationin" remains in URL
![image](https://github.com/user-attachments/assets/c28ee42f-8ec3-4715-9809-3d4ea015d4e2)

**Comment by birko999** [comment]
Hello @briangann
Have you got any update on this issue, please?
Thank you very much

**Comment by dequeee** [comment]
There are few things to edit after upgrading.

Grafana 11.1 only load polystat 2.0.0 >, so you have to upgrade also polystat panel.

Upgrading from panel polystat version 1.12.x to 2.1.x requires few changes in complex dashboards.

Upgrading a panel with complex overrides and composites requires to add / at the start and at the bottom of the metric, which before wasn't required.

So this problem with metrics can lead to increasing the number of cells. which also lead to an error:

Cannot read properties of undefined (reading 'x')

if the number of cells excedes the limit configured in the layout section.

Metrics changes also afflicts cells colors. i found out that now sometimes value mapping conflicts with overrides. so i used value mapping color setting for the cells color configuration instead of overrides.

I hope this could be useful.
