### ISSUE TITLE
Automatic Composites

### ISSUE THREAD

**Issue by EEParker** [grafana/grafana-polystat-panel#45]
Is it possible to automatically create composites with a regex scheme? 
In my case I am using InfluxDb and I have three metrics, CPU, available RAM and available DISK space. These metrics are returned for all servers in a data center.

I would like to be able to have the composite be generated for each server in the result set. The data center is a variable, and changes the servers. With 10-20 servers per data center, manually creating composites is very time consuming.

![image](https://user-images.githubusercontent.com/15874076/51550337-cb076100-1e31-11e9-8515-8ceb548ed7c5.png)

![image](https://user-images.githubusercontent.com/15874076/51550356-d35f9c00-1e31-11e9-9e46-4883d404b625.png)
![image](https://user-images.githubusercontent.com/15874076/51550475-03a73a80-1e32-11e9-9133-73787d8f4e3d.png)
![image](https://user-images.githubusercontent.com/15874076/51550489-099d1b80-1e32-11e9-81ba-df7a236fd8ce.png)
![image](https://user-images.githubusercontent.com/15874076/51550511-13bf1a00-1e32-11e9-8f13-4408e52ea344.png)

**Comment by briangann** [comment]
This would be a great feature to add. Not entirely sure how to specify it in the editor though.

**Comment by anthraxn8b** [comment]
> This would be a great feature to add. Not entirely sure how to specify it in the editor though.

IMHO (prometheus user): Should this not be something like "Auto Composite By Regex" which can be pointing to a label or the metric name?

**Example**
1. Composite Typ (Selection) [AUTO|MANUAL]
2. For "AUTO": Value Type To Analyse (Selection) [METRIC-NAME|LABEL-NAME]
3. For "AUTO": Regex (String)

**Comment by briangann** [comment]
Going to work on this next, @anthraxn8b that's a great suggestion.

**Comment by igorKryvenko** [comment]
Hi all. Any updates about this issue? Interested in this one as well.

**Comment by riedoi** [comment]
Hi
Me too, would be very nice to have this.

**Comment by kssanthosh** [comment]
Did anyone find any solution for this? Please let me know I need this feature to configure the dashboard as expected.

**Comment by srclosson** [comment]
Implemented and checked in as part of https://github.com/grafana/grafana-polystat-panel/commit/a4da8867e1cee6adb2817c7a8f96dc13398e64e5

Important to note, If you have a variable ($allServers) and want your metrics to also match, label your metrics with the server name, then use the template $compositeName in the metric name. 

`/^$compositeName:(?<name>.*)$/`
In this case, the metric name I actually want to display is labelled with `name`. There is a new input box by the metric configuration called alias. If using a named match regex, use the name as the template (in this case $name) to remove the composite name from the front. If not using named regex's, use $1,$2,etc. as you would in a perl style regular expression substitution in the alias field.

Hope this makes sense.

Note: Not officially released yet

**Comment by arodrime** [comment]
Hey, I'm also willing to compose over an unknown number of servers as I'm templating for people to reuse the charts. I can't know in advance the name or the number of servers. Anyway, this makes sense even for people who got more than a few servers. I was happy to see a patch, and sad it wasn't released yet.

@briangann / @srclosson did this change finally reach master and a released version of polystat panel? If not, what is missing and how can I give a try to this code in my local grafana or maybe contribute to make this feature a reality for people using the polystat plugin?

Thanks for the work on this plugin and this feature especially.

**Comment by matletix** [comment]
Looks like this got implemented in #96. @briangann should this be closed ?

**Comment by mjiderhamn** [comment]
> Looks like this got implemented in #96. @briangann should this be closed ?

I think at the very least, this needs to be properly documented.

@srclosson :
> Hope this makes sense.

Unfortunately, no. :-(

From the example screenshots in the original request, what should `Alias by`, `Composite Name`, `Metric` and `Alias` be set to?
I'm trying  `Composite Name` = `$tag_host` and `Metric` = `$tag_host CPU`,  `/^$compositeName:(?<tag_host>.*)$/`, `/^$compositeName:(?<tag_host>.*) CPU$/`, `/^$compositeName:(?<CPU>.*)$/` etc etc but I'm not getting any composites.

**Comment by mjiderhamn** [comment]
So, after some debugging I got this working. Here is how:

1. Create a dashboard query variable to enlist all the possible composite names. In the case of InfluxDB and the `win_cpu` metric you may want do use a query like `SELECT "host" FROM ( SELECT "Percent_Processor_Time","host" FROM "win_cpu" WHERE $timeFilter)`, and set it to _Refresh On Time Range Change_. In this example I call this variable `host`. You may _Hide_ the _Variable_, but **make sure to enable _Include All option_**.
![image](https://user-images.githubusercontent.com/837073/106630507-2f5e6e80-657c-11eb-97a6-c2539ec47721.png)
2. Make your Query result include the composite name so that it can be identified for grouping. In the case of InfluxDB you can put `$tag_host` in the _Alias By_ field just like in the original request.
![image](https://user-images.githubusercontent.com/837073/106629612-494b8180-657b-11eb-9227-471376d0cb3b.png)
3. Configure _Composites_ for the Polystat panel.
3.1 Set _Composite Name_ = the dashboard variable from step 1 - in our case `$host`.
3.2 Add Metrics series and set _Metric name_ to match how we named the metrics in step 2, but replace the composite name (in our case the host name/`host` tag value) with `$compositeName`. Set _Alias_ to whatever should be displayed in the hoover popup for the metric.
![image](https://user-images.githubusercontent.com/837073/106630067-c7a82380-657b-11eb-9ff3-aa9ef2984c78.png)

Result:
![image](https://user-images.githubusercontent.com/837073/106631008-a3007b80-657c-11eb-8f87-995278f1ac7a.png)

**Comment by MAzZYBig** [comment]
@mjiderhamn Many thanks to you for this guide!

Advice to everyone who tries to make these composites. If you haven't enabled option **Include All option** from the very beginning, you will get many pain. In this case you should unhide your variable, select value **All**, and then hide it again. Otherwise, it will show you only one composite.

And one more question. Does anyone know how to use current variable value for each composite to show it in the Alias field? I can't get it.
